steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'bajaj-app'   
    - '--source'
    - '.'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
